# Generated by Django 2.1.1 on 2018-10-01 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20181001_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='batch',
            field=models.IntegerField(default='2016', validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Audibility',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Behaviour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Method_of_teaching',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Punctuality',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Section_name',
            field=models.ForeignKey(default='S09', on_delete=django.db.models.deletion.CASCADE, to='mysite.Section'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Subject_knowledge',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Syllabus_coverage',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rollno',
            field=models.IntegerField(default='03215603116'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student_name',
            field=models.CharField(default='Naman Sharma', max_length=120),
        ),
        migrations.AlterField(
            model_name='section',
            name='Section_name',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=10),
        ),
    ]
