# Generated by Django 2.1.1 on 2018-10-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20181001_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Subject')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='subject_name',
            field=models.ManyToManyField(to='mysite.TeacherSubjectMapping'),
        ),
    ]
